using CodeKids.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeKids.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826120000_AddSubjectUnitsAndCurriculumFields")]
    public class AddSubjectUnitsAndCurriculumFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "GradeId" integer NULL;
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "TermId" integer NULL;
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "TrackCode" character varying(40) NOT NULL DEFAULT '';
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "TrackName" character varying(80) NOT NULL DEFAULT '';
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "VerificationStatus" character varying(80) NOT NULL DEFAULT '';
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "SourceTocUrl" character varying(500) NOT NULL DEFAULT '';
                ALTER TABLE "Subjects" ADD COLUMN IF NOT EXISTS "Variants" character varying(400) NOT NULL DEFAULT '';

                DO $$ BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Subjects_Grades_GradeId'
                    ) THEN
                        ALTER TABLE "Subjects"
                            ADD CONSTRAINT "FK_Subjects_Grades_GradeId"
                            FOREIGN KEY ("GradeId") REFERENCES "Grades" ("Id") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_Subjects_GradeId" ON "Subjects" ("GradeId");
                CREATE INDEX IF NOT EXISTS "IX_Subjects_GradeId_TermId_Code_TrackCode"
                    ON "Subjects" ("GradeId", "TermId", "Code", "TrackCode");

                CREATE TABLE IF NOT EXISTS "SubjectUnits" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "SubjectId" integer NOT NULL,
                    "Title" character varying(300) NOT NULL,
                    "SortOrder" integer NOT NULL,
                    "VerificationStatus" character varying(80) NOT NULL DEFAULT '',
                    "TenantId" character varying(64) NULL,
                    CONSTRAINT "PK_SubjectUnits" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_SubjectUnits_Subjects_SubjectId"
                        FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "SubjectUnitLessons" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "SubjectUnitId" integer NOT NULL,
                    "Title" character varying(300) NOT NULL,
                    "SortOrder" integer NOT NULL,
                    "TenantId" character varying(64) NULL,
                    CONSTRAINT "PK_SubjectUnitLessons" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_SubjectUnitLessons_SubjectUnits_SubjectUnitId"
                        FOREIGN KEY ("SubjectUnitId") REFERENCES "SubjectUnits" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_SubjectUnits_SubjectId_SortOrder"
                    ON "SubjectUnits" ("SubjectId", "SortOrder");
                CREATE INDEX IF NOT EXISTS "IX_SubjectUnits_TenantId" ON "SubjectUnits" ("TenantId");
                CREATE INDEX IF NOT EXISTS "IX_SubjectUnitLessons_SubjectUnitId_SortOrder"
                    ON "SubjectUnitLessons" ("SubjectUnitId", "SortOrder");
                CREATE INDEX IF NOT EXISTS "IX_SubjectUnitLessons_TenantId" ON "SubjectUnitLessons" ("TenantId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "SubjectUnitLessons";
                DROP TABLE IF EXISTS "SubjectUnits";
                DROP INDEX IF EXISTS "IX_Subjects_GradeId_TermId_Code_TrackCode";
                DROP INDEX IF EXISTS "IX_Subjects_GradeId";
                ALTER TABLE "Subjects" DROP CONSTRAINT IF EXISTS "FK_Subjects_Grades_GradeId";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "GradeId";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "TermId";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "TrackCode";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "TrackName";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "VerificationStatus";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "SourceTocUrl";
                ALTER TABLE "Subjects" DROP COLUMN IF EXISTS "Variants";
                """);
        }
    }
}
