namespace CodeKids.Application.Features.Courses;

public sealed record CourseDto(
    Guid Id,
    string Title,
    string Theme,
    string Description,
    int AgeMin,
    int AgeMax,
    string? Term,
    int? Grade,
    int? StageId,
    string? SchoolType,
    int SortOrder,
    int? ExternalSubjectId,
    IReadOnlyList<CourseUnitDto> Units,
    IReadOnlyList<CourseLessonDto> Lessons,
    IReadOnlyList<CourseQuizDto> Quizzes,
    IReadOnlyList<CourseVideoSummaryDto> Videos,
    string SubjectCode = "",
    string Category = "",
    string TrackCode = "",
    string TrackName = "",
    string VerificationStatus = "",
    string SourceTocUrl = "",
    string Notes = "",
    string Variants = "",
    bool StudentAskEnabled = false);
